// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.WebsitetoPDF
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("marginLeft")]
        public string MarginLeft { get; set; }

        [JsonProperty("marginRight")]
        public string MarginRight { get; set; }

        [JsonProperty("marginTop")]
        public string MarginTop { get; set; }

        [JsonProperty("marginBottom")]
        public string MarginBottom { get; set; }

        [JsonProperty("landscape")]
        public bool Landscape { get; set; }

        [JsonProperty("pdfName")]
        public string PdfName { get; set; }

        [JsonProperty("expires")]
        public long Expires { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("downloadURL")]
        public Uri DownloadUrl { get; set; }
    }
}
